[package]
name = "web_fetch"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "lib.rs"

[dependencies]
rquickjs = { version = "=0.11.0", features = ["classes", "properties", "loader"] }
smol = { version = "2.0.2" }
smol-hyper = { version = "0.1.1" }
hyper = { version = "1.8.1", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1.19", default-features = false }
http-body-util = { version = "0.1.3" }
async-native-tls = { version = "0.5.0", optional = true }
futures-io = { version = "0.3.31", optional = true }
bytes = { version = "1.11.0" }
once_cell = { version = "1.21.3" }
serde_json = { version = "1.0.148" }
utils = { path = "../utils" }

[features]
default = []
native-tls = ["dep:async-native-tls", "dep:futures-io"]
