[package]
name = "mdeno"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "mdeno"
path = "src/lib.rs"

[[bin]]
name = "mdeno"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap_lex = "0.7.5"
libsui = "0.12.2"
mdeno_runtime = { path = "runtime" }
utils = { path = "../modules/utils" }
oxc_allocator = "0.105"
oxc_ast = "0.105"
oxc_codegen = "0.105"
oxc_parser = "0.105"
oxc_semantic = "0.105"
oxc_span = "0.105"
oxc_transformer = "0.105"
ureq = { version = "3.1.4", default-features = false, features = ["native-tls", "gzip", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
tempfile = "3.24.0"

[features]
default = ["deno_os"]
deno_os = ["mdeno_runtime/deno_os"]
vendored-openssl = ["mdeno_runtime/vendored-openssl"]
