[package]
name = "web_encoding"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "lib.rs"

[dependencies]
rquickjs = { version = "=0.11.0", features = ["classes", "properties", "loader"] }
base64 = "0.22.1"
serde_json = "1.0.145"
utils = { path = "../utils" }
