[package]
name = "deno_common"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rquickjs = { version = "=0.11.0", features = ["classes", "properties", "loader"] }

[lints]
workspace = true
